import { useState } from 'react'
import type { ScreenReviewContextResponse } from '../../types/admin'
import { EmptyState } from '../../components/EmptyState'
import { StatusBadge } from '../../components/StatusBadge'

type Tab = 'summary' | 'structure' | 'inference' | 'traceability'
const tabs: { id: Tab; label: string }[] = [{ id: 'summary', label: 'Resumen' }, { id: 'structure', label: 'Estructura' }, { id: 'inference', label: 'Inferencia' }, { id: 'traceability', label: 'Trazabilidad' }]
const shortened = (value: string | null) => value ? value.length > 22 ? `${value.slice(0, 10)}…${value.slice(-8)}` : value : 'No disponible en el snapshot de demostración'
function List({ values, empty = 'No disponible en el snapshot de demostración.' }: { values: string[]; empty?: string }) { return values.length ? <ul className="detail-list">{values.map((value) => <li key={value}>{value}</li>)}</ul> : <EmptyState>{empty}</EmptyState> }
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div> }
export function ScreenDetail({ context, onNavigate }: { context: ScreenReviewContextResponse; onNavigate: (id: string) => void }) {
  const [tab, setTab] = useState<Tab>('summary'); const p = context.effective_payload; const e = context.structural_evidence; const proposal = context.active_proposal
  return <article className="detail">
    <header className="detail-header"><div><p className="breadcrumb">{context.erp.name} <span>/</span> {context.module?.name ?? 'Sin módulo'}</p><div className="title-line"><h1>{context.screen.title ?? 'Pantalla sin título'}</h1><StatusBadge status={context.semantic_state} /></div><p className="route">{context.screen.route ?? 'Ruta no disponible en el snapshot de demostración'}</p></div><div className="position"><span>Posición en el módulo</span><strong>{context.navigation.module_screen_position} de {context.navigation.module_screen_total}</strong></div></header>
    <div className="state-strip"><span>Estructura <StatusBadge status={context.screen.structural_review_status} /></span><span>Semántica <StatusBadge status={context.semantic_state} /></span><span>Evidencia <b>{e.evidence_available ? 'Disponible' : 'No disponible'}</b></span></div>
    <section className="metrics" aria-label="Indicadores"><Metric label="Capabilities" value={p?.supported_capabilities.length ?? 0}/><Metric label="Propuesta activa" value={proposal ? '1' : 'Ninguna'}/><Metric label="Acciones de revisión" value={context.traceability.review_action_count}/><Metric label="Evidencia vs. estructura" value={proposal && (proposal.historical_structure_hash === null || proposal.diagnostic === 'Comparación no disponible en el snapshot de demostración.') ? 'No disponible en el snapshot de demostración' : proposal?.evidence_matches_current_structure ? 'Coincide' : proposal ? 'Difiere' : 'No aplica'}/></section>
    <div className="tabs" role="tablist" aria-label="Detalle de pantalla">{tabs.map(({ id, label }) => <button key={id} role="tab" aria-selected={tab === id} onClick={() => setTab(id)}>{label}</button>)}</div>
    <section className="tab-panel" role="tabpanel">
      {tab === 'summary' && <><Section title="Propósito"><p className="purpose">{p?.purpose_summary ?? 'La pantalla no tiene una propuesta semántica activa.'}</p></Section><Section title="Capabilities">{p?.supported_capabilities.length ? <div className="capabilities">{p.supported_capabilities.map((capability) => <div className="capability" key={capability.statement}><span className="check" aria-hidden="true">✓</span><div><strong>{capability.statement}</strong><small>Evidencia: {capability.evidence_refs.join(', ')}</small></div></div>)}</div> : <EmptyState>No hay capabilities disponibles.</EmptyState>}</Section><div className="two-cols"><Section title="Limitaciones"><List values={p?.limitations ?? []}/></Section><Section title="Incertidumbres"><List values={p?.uncertainties ?? []}/></Section></div><div className="notice"><strong>Flujo read-only</strong><p>Las acciones de aprobar, corregir y rechazar se habilitarán en la siguiente fase.</p></div></>}
      {tab === 'structure' && <div className="structure-grid"><EvidenceGroup title="Campos" values={e.fields.map((x) => x.label)}/><EvidenceGroup title="Controles" values={e.controls.map((x) => x.label)}/><EvidenceGroup title="Tablas y columnas" values={e.tables.map((x) => `${x.name}: ${x.columns.map((c) => c.label).join(', ')}`)}/><EvidenceGroup title="Estados UI" values={e.ui_states.map((x) => x.title)}/><EvidenceGroup title="Eventos" values={e.events.map((x) => x.label)}/><EvidenceGroup title="Transiciones" values={e.transitions.map((x) => x.transition_id)}/><EvidenceGroup title="IDs de evidencia" values={e.evidence_ids}/><EvidenceGroup title="Advertencias" values={e.warnings}/></div>}
      {tab === 'inference' && <><div className="info-grid"><Metric label="Semantic ID" value={proposal?.summary.semantic_id ?? 'No disponible'}/><Metric label="Tipo semántico" value={proposal?.summary.semantic_type ?? 'No disponible'}/><Metric label="Estado" value={proposal?.summary.current_review_status ?? 'Sin propuesta'}/><Metric label="Modelo" value={proposal?.summary.generation_model ?? 'No disponible'}/><Metric label="Prompt version" value={proposal?.summary.prompt_version ?? 'No disponible'}/><Metric label="Evidence hash" value={shortened(proposal?.summary.evidence_hash ?? null)}/></div><Section title="Snapshot histórico"><p>{proposal?.evidence.evidence_available ? `${proposal.evidence.evidence_ids.length} referencias de evidencia disponibles.` : 'Evidencia histórica no disponible.'}</p></Section><Section title="Comparación con la estructura actual"><p>{proposal && (proposal.historical_structure_hash === null || proposal.diagnostic === 'Comparación no disponible en el snapshot de demostración.') ? 'No disponible en el snapshot de demostración' : proposal?.evidence_matches_current_structure ? 'La evidencia histórica coincide con la estructura actual.' : proposal ? 'La evidencia histórica difiere de la estructura actual.' : 'No existe una propuesta para comparar.'}</p></Section></>}
      {tab === 'traceability' && <><div className="info-grid"><Metric label="Propuestas" value={context.traceability.proposal_count}/><Metric label="Acciones de revisión" value={context.traceability.review_action_count}/><Metric label="Identidad verificada" value={context.reviewer_identity_verified ? 'Sí' : 'No'}/></div><Section title="IDs de evidencia"><List values={context.traceability.evidence_ids}/></Section><Section title="Historial">{context.review_history.length ? <List values={context.review_history.map((item) => `${item.action}: ${item.previous_status} → ${item.new_status}`)}/> : <EmptyState>No existen acciones de revisión registradas.</EmptyState>}</Section><Section title="Advertencias"><List values={context.traceability.warnings} empty="No existen advertencias."/></Section><div className="navigation"><button disabled={!context.navigation.previous_screen_id} onClick={() => context.navigation.previous_screen_id && onNavigate(context.navigation.previous_screen_id)}>← Pantalla anterior</button><button disabled={!context.navigation.next_screen_id} onClick={() => context.navigation.next_screen_id && onNavigate(context.navigation.next_screen_id)}>Pantalla siguiente →</button></div></>}
    </section>
  </article>
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="section"><h2>{title}</h2>{children}</section> }
function EvidenceGroup({ title, values }: { title: string; values: string[] }) { return <section className="evidence-group"><h2>{title}<span>{values.length}</span></h2><List values={values}/></section> }
